export function getLanguageIdForFileExtension(extension: string): string {
    const languageId = fileExtensionToLanguageId[extension];
    if (!languageId) {
        throw new TypeError(`no language id found for extension: '${extension}'`);
    }
    return languageId;
}

export const fileExtensionToLanguageId: Record<string, string> = {
    '.abap': 'abap',
    '.bat': 'bat',
    '.bib': 'bibtex',
    '.clj': 'clojure',
    '.coffee': 'coffeescript',
    '.c': 'c',
    '.cpp': 'cpp',
    '.cc': 'cpp',
    '.cxx': 'cpp',
    '.cs': 'csharp',
    '.docker-compose.yml': 'dockercompose',
    '.css': 'css',
    '.cu': 'cuda-cpp',
    '.cuh': 'cuda-cpp',
    '.d': 'd',
    '.dart': 'dart',
    '.pas': 'pascal',
    '.diff': 'diff',
    Dockerfile: 'dockerfile',
    '.erl': 'erlang',
    '.fs': 'fsharp',
    '.fsx': 'fsharp',
    '.gitcommit': 'git-commit',
    '.gitrebase': 'git-rebase',
    '.go': 'go',
    '.groovy': 'groovy',
    '.hbs': 'handlebars',
    '.haml': 'haml',
    '.hs': 'haskell',
    '.html': 'html',
    '.ini': 'ini',
    '.cfg': 'ini',
    '.java': 'java',
    '.js': 'javascript',
    '.jsx': 'javascriptreact',
    '.json': 'json',
    '.jsonc': 'jsonc',
    '.jl': 'julia',
    '.latex': 'latex',
    '.less': 'less',
    '.lua': 'lua',
    Makefile: 'makefile',
    '.md': 'markdown',
    '.mm': 'objective-cpp',
    '.m': 'objective-c',
    '.ml': 'ocaml',
    '.pascal': 'pascal',
    '.pl': 'perl',
    '.pm': 'perl',
    '.php': 'php',
    '.txt': 'plaintext',
    '.ps1': 'powershell',
    '.pug': 'pug',
    '.jade': 'pug',
    '.py': 'python',
    '.r': 'r',
    '.cshtml': 'razor',
    '.rb': 'ruby',
    '.rs': 'rust',
    '.scss': 'scss',
    '.sass': 'sass',
    '.shader': 'shaderlab',
    '.sh': 'shellscript',
    '.bash': 'shellscript',
    '.zsh': 'shellscript',
    '.slim': 'slim',
    '.sql': 'sql',
    '.styl': 'stylus',
    '.svelte': 'svelte',
    '.swift': 'swift',
    '.ts': 'typescript',
    '.tsx': 'typescriptreact',
    '.tex': 'tex',
    '.vb': 'vb',
    '.vue': 'vue',
    '.vue.html': 'vue-html',
    '.xml': 'xml',
    '.xsl': 'xsl',
    '.yml': 'yaml',
    '.yaml': 'yaml',
};
